/**
 * Two projects, because the tiers answer different questions and must be
 * runnable separately in CI.
 *
 *   unit         jsdom, no I/O, fakes and fixtures
 *   integration  the real collector against real repositories on disk
 *
 * The e2e tier is Playwright (`playwright.config.ts`), not jest — jsdom has no
 * layout engine, so every element reports a zero-sized box and anything about
 * what a person can actually see is unanswerable here.
 */

/** @type {import('jest').Config} */
const shared = {
  // ESM, not the default CJS transform: this package ships ESM source and its
  // `.js` specifiers are what the published package really needs. Requires
  // NODE_OPTIONS=--experimental-vm-modules, set in the `test` scripts.
  preset: "ts-jest/presets/default-esm",
  // `.tsx` as well as `.ts`. Omitting it loads the component modules as
  // CommonJS, where the first ESM-only import fails with "Must use import to
  // load ES Module" — pointing at the dependency rather than at this list.
  extensionsToTreatAsEsm: [".ts", ".tsx"],
  moduleNameMapper: {
    // Source imports carry `.js` specifiers because that is what real ESM
    // requires of the published package. TypeScript resolves them back to `.ts`
    // itself; Jest does not, so the extension is stripped here.
    "^(\\.{1,2}/.*)\\.js$": "$1",
    // `styled-system` is generated by `panda codegen` into the repo root and
    // resolved via tsconfig baseUrl at typecheck time. Jest does not read
    // baseUrl, so it needs the mapping spelled out or every styled import dies
    // with "Cannot find module 'styled-system/css'".
    "^styled-system/(.*)$": "<rootDir>/styled-system/$1",
    // The server imports the package by its public specifier, as a consumer
    // does. Anchored with `$` so the bare entry point cannot swallow the
    // subpaths. This is one of four places these aliases are written —
    // tsconfig.json, server/tsconfig.json and server/vite.config.ts are the
    // others — and they must agree, because each tool reads only its own.
    "^@stonedogcode/tests$": "<rootDir>/src/index.ts",
    "^@stonedogcode/tests/node$": "<rootDir>/src/node/index.ts",
    "^@stonedogcode/tests/styled$": "<rootDir>/src/styled/index.ts",
  },
  transform: {
    "^.+\\.tsx?$": ["ts-jest", { useESM: true }],
  },
  // `@stonedogcode/style` ships TypeScript SOURCE rather than a bundle (Panda
  // has to statically parse it at the consumer's build). Jest does not
  // transform node_modules by default, so its `.ts` files reach Node's ESM
  // loader raw and fail on the first `export type`. Named explicitly rather
  // than opening node_modules wholesale: everything else here is already ESM.
  transformIgnorePatterns: ["/node_modules/(?!@stonedogcode/style/)", "\\.pnp\\.[^\\\\]+$"],
};

module.exports = {
  projects: [
    {
      ...shared,
      displayName: "unit",
      testEnvironment: "jsdom",
      testMatch: ["<rootDir>/src/**/__tests__/**/*.test.{ts,tsx}"],
      setupFilesAfterEnv: ["<rootDir>/test/setup-unit.ts"],
    },
    {
      ...shared,
      displayName: "integration",
      testEnvironment: "node",
      testMatch: ["<rootDir>/test/integration/**/*.test.ts"],
      // `testTimeout` is not honoured inside a `projects` entry on Jest 29, so
      // the real filesystem walks set their own budget from a setup file.
      setupFilesAfterEnv: ["<rootDir>/test/setup-integration.ts"],
    },
  ],
  collectCoverageFrom: ["src/**/*.{ts,tsx}", "!src/**/__tests__/**", "!src/index.ts"],
};
