import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";

import { defineConfig } from "vite";
import react from "@vitejs/plugin-react";

import { fixtureApiPlugin } from "./middleware/fixtures.js";

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, "..");

export default defineConfig({
  plugins: [react(), fixtureApiPlugin()],
  resolve: {
    /**
     * The FOURTH place these aliases are written — tsconfig.json,
     * server/tsconfig.json and jest.config.cjs are the others. They must agree,
     * and each exists because the tool reading it knows nothing of the others.
     *
     * All of them point at `src/`, which is what stops the server silently
     * exercising a published version instead of this branch.
     */
    alias: {
      "@stonedogcode/tests/styled": resolve(repoRoot, "src/styled/index.ts"),
      "@stonedogcode/tests": resolve(repoRoot, "src/index.ts"),
      // Generated by `panda codegen` into the repo root and resolved via
      // tsconfig baseUrl at typecheck time. Vite does not read baseUrl.
      "styled-system": resolve(repoRoot, "styled-system"),
    },
  },
  server: { port: 5178 },
});
